"""Compile a question's extracted concepts to a PDF via tectonic.

Reuses the markdown+LaTeX conversion pipeline from ``issue_pdf`` so that the
concept definitions (which contain inline ``$...$`` math) render correctly.
Results are cached in ``documents/pdf/`` and invalidated when the underlying
concept set changes (hash of the concept list).
"""
from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from .issue_pdf import _PREAMBLE, _TECTONIC, md_to_latex


def _wrap_notation(s: str) -> str:
    """Ensure a notation snippet is in math mode (mirrors the UI's _mathWrap)."""
    t = (s or "").strip()
    if not t:
        return ""
    if t.startswith("$") or t.startswith("\\(") or t.startswith("\\[") or t.startswith("\\begin"):
        return t
    return f"${t}$"


def _build_concepts_md(qid: str, title: str, concepts: list[dict]) -> str:
    """Assemble a markdown document (consumed by md_to_latex) from the concept list."""
    lines: list[str] = []
    lines.append(f"# {qid.upper()} — Key Concepts")
    if title and title != qid:
        lines.append(f"*{title}*")
    lines.append("")
    lines.append(f"{len(concepts)} concept{'s' if len(concepts) != 1 else ''} · Generated by ResearchMathAgent")
    lines.append("")
    for i, c in enumerate(concepts, 1):
        name = (c.get("name") or "").strip()
        cat = (c.get("category") or "").strip()
        cat_suffix = f"  ({cat})" if cat else ""
        lines.append(f"## {i}. {name}{cat_suffix}")
        lines.append("")
        notation = _wrap_notation(c.get("notation", ""))
        if notation:
            lines.append(f"**Notation:** {notation}")
            lines.append("")
        definition = (c.get("definition") or "").strip()
        if definition:
            lines.append(definition)
            lines.append("")
        example = (c.get("example") or "").strip()
        if example:
            lines.append(f"**Example:** {example}")
            lines.append("")
        related = c.get("related") or []
        if related:
            lines.append(f"**Related:** {' · '.join(related)}")
            lines.append("")
    return "\n".join(lines)


def _build_concepts_tex(qid: str, title: str, concepts: list[dict]) -> str:
    body = md_to_latex(_build_concepts_md(qid, title, concepts))
    return "\n".join([_PREAMBLE, r"\begin{document}", body, r"\end{document}"])


def _cache_paths(repo_root: Path, qid: str) -> tuple[Path, Path]:
    d = repo_root / "documents" / "pdf"
    d.mkdir(parents=True, exist_ok=True)
    return d / f"concepts_{qid}.pdf", d / f"concepts_{qid}.hash"


def _concepts_hash(concepts: list[dict]) -> str:
    s = json.dumps(concepts, sort_keys=True, ensure_ascii=False)
    return hashlib.md5(s.encode()).hexdigest()[:12]


def compile_concepts_pdf(repo_root: Path, qid: str, title: str,
                         concepts: list[dict], force: bool = False) -> dict:
    """Compile the concept list to a PDF. Returns {ok, pdf_url, log}."""
    if not concepts:
        return {"ok": False, "pdf_url": None, "log": "No concepts extracted yet for this question."}

    dest, hash_file = _cache_paths(repo_root, qid)
    cur_hash = _concepts_hash(concepts)

    if not force and dest.is_file() and hash_file.is_file():
        if hash_file.read_text().strip() == cur_hash:
            return {"ok": True, "pdf_url": f"/api/pdf/concepts_{qid}.pdf", "log": "cached"}

    tectonic = _TECTONIC if os.path.isfile(_TECTONIC) and os.access(_TECTONIC, os.X_OK) \
        else shutil.which("tectonic") or shutil.which("pdflatex")
    if not tectonic:
        return {"ok": False, "pdf_url": None, "log": "No LaTeX toolchain available"}

    tex = _build_concepts_tex(qid, title, concepts)

    with tempfile.TemporaryDirectory(prefix="rma_concepts_") as tmp:
        build = Path(tmp)
        (build / "main.tex").write_text(tex, encoding="utf-8")

        def _try_compile(cmd: list[str]) -> tuple[int, str]:
            try:
                proc = subprocess.run(cmd, cwd=build, capture_output=True, timeout=120)
                return proc.returncode, proc.stdout.decode("utf-8", "replace") + proc.stderr.decode("utf-8", "replace")
            except subprocess.TimeoutExpired:
                return 1, "Compilation timed out"

        if "tectonic" in tectonic:
            rc, log = _try_compile([tectonic, "main.tex"])
            if rc != 0:
                rc2, log2 = _try_compile([tectonic, "-Z", "continue-on-errors", "main.tex"])
                if (build / "main.pdf").is_file():
                    rc, log = 0, log2
        else:
            rc, log = _try_compile(["pdflatex", "-interaction=nonstopmode", "main.tex"])

        out_pdf = build / "main.pdf"
        if out_pdf.is_file():
            shutil.copyfile(out_pdf, dest)
            hash_file.write_text(cur_hash)
            return {"ok": True, "pdf_url": f"/api/pdf/concepts_{qid}.pdf", "log": "OK"}
        return {"ok": False, "pdf_url": None, "log": f"Build failed (exit {rc})\n{log[-3000:]}"}
